# Generated by Django 4.1 on 2022-09-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
